# This file is managed by Copier.
_commit: v0.1.0
_src_path: https://github.com/betabitplus-template-lab/sandbox-ternforge-template-py-library-20260717-r2.git
package_name: ternforge_python_consumer_r2
project_name: Ternforge Python Consumer R2
project_slug: ternforge-python-consumer-r2
